#!/usr/bin/env bash
# Single sync script for all AI tool configurations.
#
# Source of truth:
#   Rules  → AGENTS.md  (sections above the generated skills block)
#   Skills → .agents/skills/<name>/SKILL.md
#
# Outputs:
#   .claude/rules/*.md           — rules for Claude Code
#   .cursor/rules/*.mdc          — rules (alwaysApply:true) for Cursor
#   .cursor/rules/*-skill.mdc    — skills (alwaysApply:false) for Cursor
#   AGENTS.md [# Skills block]   — skills inlined at the bottom for Codex
#
# Run from repo root after any edit to AGENTS.md or a SKILL.md.

set -e
cd "$(git rev-parse --show-toplevel)"
mkdir -p .cursor/rules .claude/rules

AGENTS_FILE="AGENTS.md"
SKILLS_MARKER="<!-- SKILLS: generated by sync-agents.sh"

# ── 1. Extract rules-only content (above the generated block) ────────────────
rules_content=$(awk "/^${SKILLS_MARKER}/{exit} {print}" "$AGENTS_FILE")

# ── 2. Sync rules → .claude/rules/*.md and .cursor/rules/*.mdc ──────────────
rm -f .cursor/rules/*.mdc .claude/rules/*.md

printf '%s\n' "$rules_content" | awk '
  BEGIN { first_hr = 0; name = "" }
  /^---$/ {
    first_hr = 1
    if (name != "") { close(out_cursor); close(out_claude); name = "" }
    next
  }
  /^# / && first_hr {
    if (name != "") { close(out_cursor); close(out_claude) }
    title = substr($0, 3)
    name = tolower(title)
    gsub(/[^a-z0-9]+/, "-", name)
    gsub(/^-|-$/, "", name)
    out_cursor = ".cursor/rules/" name ".mdc"
    out_claude = ".claude/rules/" name ".md"
    print "---" > out_cursor
    print "description: " title > out_cursor
    print "alwaysApply: true" > out_cursor
    print "---" > out_cursor
    print "" > out_cursor
    print $0 > out_cursor
    print "---" > out_claude
    print "description: " title > out_claude
    print "---" > out_claude
    print "" > out_claude
    print $0 > out_claude
    next
  }
  name != "" { print $0 >> out_cursor; print $0 >> out_claude }
  END { if (name != "") { close(out_cursor); close(out_claude) } }
'

echo "  Rules synced  → .cursor/rules/*.mdc, .claude/rules/*.md"

# ── 3. Sync skills → .cursor/rules/*-skill.mdc ──────────────────────────────
rm -f .cursor/rules/*-skill.mdc

for skill_file in .agents/skills/*/SKILL.md; do
  [ -f "$skill_file" ] || continue
  skill_name=$(awk '/^name:/{sub(/^name: */, ""); print; exit}' "$skill_file")
  skill_desc=$(awk '/^description:/{sub(/^description: */, ""); print; exit}' "$skill_file")
  [ -z "$skill_name" ] && continue

  {
    echo "---"
    echo "description: ${skill_desc}"
    echo "alwaysApply: false"
    echo "---"
    echo ""
    awk 'BEGIN{n=0} /^---/{n++; if(n==2){found=1; next}} found{print}' "$skill_file"
  } > ".cursor/rules/${skill_name}-skill.mdc"
done

echo "  Skills synced → .cursor/rules/*-skill.mdc"

# ── 4. Regenerate # Skills block in AGENTS.md for Codex ─────────────────────
# Skills are inlined in full so Codex doesn't need to open separate files.
# Headings inside each skill body are demoted by 2 levels to fit the hierarchy.
{
  printf '%s\n' "$rules_content"
  echo ""
  echo "${SKILLS_MARKER} — do not edit below this line -->"
  echo ""
  echo "# Skills"
  echo ""
  echo "Available runbooks in \`.agents/skills/\`. Read the steps below before performing each task."
  echo ""

  for skill_file in .agents/skills/*/SKILL.md; do
    [ -f "$skill_file" ] || continue
    skill_name=$(awk '/^name:/{sub(/^name: */, ""); print; exit}' "$skill_file")
    [ -z "$skill_name" ] && continue

    echo "## ${skill_name}"
    echo ""
    awk 'BEGIN{n=0} /^---/{n++; if(n==2){found=1; next}} found{
      if ($0 ~ /^### /) { sub(/^### /, "##### ") }
      else if ($0 ~ /^## /) { sub(/^## /, "#### ") }
      else if ($0 ~ /^# /) { sub(/^# /, "### ") }
      print
    }' "$skill_file"
    echo ""
  done
} > "${AGENTS_FILE}.tmp" && mv "${AGENTS_FILE}.tmp" "$AGENTS_FILE"

echo "  Skills block regenerated in AGENTS.md"
echo ""
echo "Done. Claude Code, Cursor, and Codex are in sync."
